version: "3.9"

services:
  web:
    build: .
    container_name: integrated-outbreak-web
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - .:/var/www/integrated-outbreak-system/app
    command: air cmd/web/main.go -b 0.0.0.0
    depends_on:
      - db
    networks:
      - sso_network

  db:
    image: postgres:alpine
    container_name: integrated-outbreak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      - ./01_ios_october.sql:/docker-entrypoint-initdb.d/01_ios_october.sql:ro
      - ./migrations/048_create_surveys_and_survey_questions_tables.sql:/docker-entrypoint-initdb.d/048_create_surveys_and_survey_questions_tables.sql:ro
    networks:
      - sso_network

volumes:
  postgres-db-data:
    driver: local

networks:
  sso_network:
    external: true
