package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// Treatment represents a row from 'public.treatment'.
type Treatment struct {
	TreatmentID int `json:"treatment_id"` // treatment_id
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Treatment] exists in the database.
func (t *Treatment) Exists() bool {
	return t._exists
}

// Deleted returns true when the [Treatment] has been marked for deletion
// from the database.
func (t *Treatment) Deleted() bool {
	return t._deleted
}

// Insert inserts the [Treatment] to the database.
func (t *Treatment) Insert(ctx context.Context, db DB) error {
	switch {
	case t._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case t._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.treatment (treatment_id) VALUES ($1) RETURNING treatment_id`
	// run
	logf(sqlstr, t.TreatmentID)
	if err := db.QueryRowContext(ctx, sqlstr, t.TreatmentID).Scan(&t.TreatmentID); err != nil {
		return logerror(err)
	}
	// set exists
	t._exists = true
	return nil
}

// Update updates a [Treatment] in the database.
func (t *Treatment) Update(ctx context.Context, db DB) error {
	switch {
	case !t._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case t._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.treatment SET treatment_id = $1 WHERE treatment_id = $2`
	// run
	logf(sqlstr, t.TreatmentID, t.TreatmentID)
	if _, err := db.ExecContext(ctx, sqlstr, t.TreatmentID, t.TreatmentID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Treatment] to the database.
func (t *Treatment) Save(ctx context.Context, db DB) error {
	if t.Exists() {
		return t.Update(ctx, db)
	}
	return t.Insert(ctx, db)
}

// Upsert performs an upsert for [Treatment].
func (t *Treatment) Upsert(ctx context.Context, db DB) error {
	switch {
	case t._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.treatment (treatment_id) VALUES ($1) ON CONFLICT (treatment_id) DO UPDATE SET treatment_id = EXCLUDED.treatment_id`
	// run
	logf(sqlstr, t.TreatmentID)
	if _, err := db.ExecContext(ctx, sqlstr, t.TreatmentID); err != nil {
		return logerror(err)
	}
	// set exists
	t._exists = true
	return nil
}

// Delete deletes the [Treatment] from the database.
func (t *Treatment) Delete(ctx context.Context, db DB) error {
	switch {
	case !t._exists: // doesn't exist
		return nil
	case t._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.treatment WHERE treatment_id = $1`
	// run
	logf(sqlstr, t.TreatmentID)
	if _, err := db.ExecContext(ctx, sqlstr, t.TreatmentID); err != nil {
		return logerror(err)
	}
	// set deleted
	t._deleted = true
	return nil
}

// TreatmentByTreatmentID retrieves a row from 'public.treatment' as a [Treatment].
//
// Generated from index 'treatment_pkey'.
func TreatmentByTreatmentID(ctx context.Context, db DB, treatmentID int) (*Treatment, error) {
	// query
	const sqlstr = `SELECT treatment_id FROM public.treatment WHERE treatment_id = $1`
	// run
	logf(sqlstr, treatmentID)
	t := Treatment{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, treatmentID).Scan(&t.TreatmentID); err != nil {
		return nil, logerror(err)
	}
	return &t, nil
}
