CREATE TABLE measles_case_investigations (
    id SERIAL PRIMARY KEY,
    epid_no VARCHAR(50),
    lab_no VARCHAR(50),
    visit_date DATE,
    health_unit VARCHAR(100),
    district VARCHAR(100),
    patient_type VARCHAR(20),
    patient_no VARCHAR(50),
    -- Demographic Details
    onset_district VARCHAR(100),
    reporting_unit VARCHAR(100),
    patient_name VARCHAR(100),
    sex VARCHAR(10),
    age_months INT,
    dob DATE,
    head_of_household VARCHAR(100),
    guardian_occupation VARCHAR(100),
    home_district VARCHAR(100),
    subcounty VARCHAR(100),
    parish VARCHAR(100),
    lc1_zone VARCHAR(100),
    lc1_chairman VARCHAR(100),
    lc1_tel VARCHAR(20),
    -- Clinical History
    fever BOOLEAN,
    fever_onset DATE,
    temperature FLOAT,
    rash BOOLEAN,
    rash_onset DATE,
    cough BOOLEAN,
    red_eyes BOOLEAN,
    running_nose BOOLEAN,
    other_complications BOOLEAN,
    complications_specify TEXT,
    outcome INT,
    vitamin_a BOOLEAN,
    vitamin_a_doses INT,
    immunisation_card_seen BOOLEAN,
    measles_doses INT,
    last_measles_vaccination DATE,
    vaccination_reason TEXT,
    diagnosis TEXT,
    -- Specimens
    blood_collection_date DATE,
    blood_sent_date DATE,
    blood_received_date DATE,
    blood_condition TEXT,
    urine_collection_date DATE,
    urine_sent_date DATE,
    urine_received_date DATE,
    urine_condition TEXT,
    form_sent_date DATE,
    form_received_date DATE,
    -- Investigators
    investigator_name VARCHAR(100),
    investigator_title VARCHAR(100),
    investigator_date DATE,
    -- Results
    serology_igm VARCHAR(50),
    serology_date DATE,
    serology_epi_sent_date DATE,
    virus_isolation_urine VARCHAR(50),
    virus_isolation_date DATE,
    final_classification INT,
    results_sent_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 