-- Add missing laboratory investigation fields to mpox_laboratory_investigations table
-- Based on the HTML form requirements

-- Add new laboratory investigation fields
ALTER TABLE mpox_laboratory_investigations 
ADD COLUMN IF NOT EXISTS total_protein NUMERIC,
ADD COLUMN IF NOT EXISTS albumin NUMERIC,
ADD COLUMN IF NOT EXISTS bilirubin_d NUMERIC,
ADD COLUMN IF NOT EXISTS lymphocytes NUMERIC,
ADD COLUMN IF NOT EXISTS monocytes NUMERIC,
ADD COLUMN IF NOT EXISTS eosinophils NUMERIC,
ADD COLUMN IF NOT EXISTS basophils NUMERIC,
ADD COLUMN IF NOT EXISTS neutrophils NUMERIC,
ADD COLUMN IF NOT EXISTS hgb NUMERIC,
ADD COLUMN IF NOT EXISTS hct NUMERIC,
ADD COLUMN IF NOT EXISTS mcv NUMERIC,
ADD COLUMN IF NOT EXISTS mch NUMERIC,
ADD COLUMN IF NOT EXISTS mchc NUMERIC,
ADD COLUMN IF NOT EXISTS rdw NUMERIC,
ADD COLUMN IF NOT EXISTS rdw_sd NUMERIC,
ADD COLUMN IF NOT EXISTS rdw_cv NUMERIC,
ADD COLUMN IF NOT EXISTS mpv NUMERIC,
ADD COLUMN IF NOT EXISTS pdw VARCHAR(50),
ADD COLUMN IF NOT EXISTS pct NUMERIC,
ADD COLUMN IF NOT EXISTS lab_other VARCHAR(100);

-- Add "not done" boolean fields for each lab test
ALTER TABLE mpox_laboratory_investigations 
ADD COLUMN IF NOT EXISTS lab_alt_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_ast_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_creatinine_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_potassium_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS total_protein_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS albumin_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_urea_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_ck_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_calcium_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_sodium_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_lymphocytes_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_monocytes_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_eosinophils_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_basophils_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_crp_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_neutrophils_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_hgb_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_hct_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_mcv_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_mch_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_mchc_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_rdw_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_rdw_sd_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_rdw_cv_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_mpv_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_pdw_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_pct_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_other_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_glucose_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_lactate_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_haemoglobin_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_bilirubin_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_bilirubin_d_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_wbc_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_platelets_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_prothrombin_notdone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_aptt_notdone BOOLEAN DEFAULT FALSE;

-- Add other test fields
ALTER TABLE mpox_laboratory_investigations 
ADD COLUMN IF NOT EXISTS other_malaria VARCHAR(20),
ADD COLUMN IF NOT EXISTS other_hiv VARCHAR(20),
ADD COLUMN IF NOT EXISTS other_syphilis VARCHAR(20),
ADD COLUMN IF NOT EXISTS other_mpox VARCHAR(20),
ADD COLUMN IF NOT EXISTS hepatitis_b VARCHAR(20),
ADD COLUMN IF NOT EXISTS hepatitis_c VARCHAR(20);

-- Add data entrant name field
ALTER TABLE mpox_laboratory_investigations 
ADD COLUMN IF NOT EXISTS data_entrant_name VARCHAR(100);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_mpox_lab_investigations_demographics_id ON mpox_laboratory_investigations(demographics_id); 