-- Add missing laboratory investigation fields to lab table
-- Based on the mpox laboratory investigations requirements

-- Add new laboratory investigation fields
ALTER TABLE public.lab 
ADD COLUMN IF NOT EXISTS total_protein NUMERIC,
ADD COLUMN IF NOT EXISTS albumin NUMERIC,
ADD COLUMN IF NOT EXISTS bilirubin_d NUMERIC,
ADD COLUMN IF NOT EXISTS lymphocytes NUMERIC,
ADD COLUMN IF NOT EXISTS monocytes NUMERIC,
ADD COLUMN IF NOT EXISTS eosinophils NUMERIC,
ADD COLUMN IF NOT EXISTS basophils NUMERIC,
ADD COLUMN IF NOT EXISTS neutrophils NUMERIC,
ADD COLUMN IF NOT EXISTS hgb NUMERIC,
ADD COLUMN IF NOT EXISTS hct NUMERIC,
ADD COLUMN IF NOT EXISTS mcv NUMERIC,
ADD COLUMN IF NOT EXISTS mch NUMERIC,
ADD COLUMN IF NOT EXISTS mchc NUMERIC,
ADD COLUMN IF NOT EXISTS rdw NUMERIC,
ADD COLUMN IF NOT EXISTS rdw_sd NUMERIC,
ADD COLUMN IF NOT EXISTS rdw_cv NUMERIC,
ADD COLUMN IF NOT EXISTS mpv NUMERIC,
ADD COLUMN IF NOT EXISTS pdw VARCHAR(50),
ADD COLUMN IF NOT EXISTS pct NUMERIC,
ADD COLUMN IF NOT EXISTS lab_other VARCHAR(100);

-- Add "not done" boolean fields for each lab test
ALTER TABLE public.lab 
ADD COLUMN IF NOT EXISTS total_protein_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS albumin_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS bilirubin_d_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lymphocytes_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS monocytes_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS eosinophils_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS basophils_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS neutrophils_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS hgb_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS hct_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS mcv_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS mch_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS mchc_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS rdw_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS rdw_sd_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS rdw_cv_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS mpv_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pdw_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pct_nd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lab_other_nd BOOLEAN DEFAULT FALSE;

-- Add other test fields
ALTER TABLE public.lab 
ADD COLUMN IF NOT EXISTS other_malaria VARCHAR(20),
ADD COLUMN IF NOT EXISTS other_hiv VARCHAR(20),
ADD COLUMN IF NOT EXISTS other_syphilis VARCHAR(20),
ADD COLUMN IF NOT EXISTS other_mpox VARCHAR(20),
ADD COLUMN IF NOT EXISTS hepatitis_b VARCHAR(20),
ADD COLUMN IF NOT EXISTS hepatitis_c VARCHAR(20);

-- Add data entrant name field
ALTER TABLE public.lab 
ADD COLUMN IF NOT EXISTS data_entrant_name VARCHAR(100);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_lab_encounter_id ON public.lab(encounter_id); 